server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: host.docker.internal:9092

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # 하트비트 간격(기본 30초)
    lease-expiration-duration-in-seconds: 30  # 만료 시간(기본 90초)
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/

feign:
  client:
    config:
      default:  # 모든 Feign 클라이언트에 적용되는 기본 설정
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic